language: java
# sudo: false
sudo: required
services:
  - docker
jdk:
  - oraclejdk8
script:
#- mvn clean install
  - mvn clean package
# deploy:
#   provider: s3
#   access_key_id: AKIAJTNAO3GPLU3O3RMA
#   secret_access_key:
#     secure: QE82Vy0rpIle+cbVAR4lR9V9v7f5XV0odwVVeQmMziYW85Wg7NHhE8jfjBB7rKxe69AGBdA+YSpHwWb3XFatYBpv8e1Lp+dxQLidO5SoVZZ4qePWoAjeAUr/7bbwSX2ssNk54JeT/4XLZWHr4S0rMOl8QyCX4V/eJIFtRb4sD+VbejkZFWFAOrGrujZfHVCII7OPyQWxErwW+rNKAdOXO/Ra4R+H9TbnDNnMfJUyxtvP++uVv4019dxCajiCWx3IIcf1OlLqcYxhjVAxf3eXtP0OPyxwqQbLbnAdvIEUkil9HlSzAR++W6nnIBozsSoMhW8bxf7qUFokGIwLx67qZ1uZMSfHMlcaEo1u63WzFloq4Pm+AkCG+KsSsqIQo22ZEMG0gm6qVSFbl1jMgzvyP8uIZ7IW1rmWDwVEYb+VD29EMz8Y+wozSzQM4CiQBnKZMMtEZmPCjzAH64jWuKpUqpKboVbgqjVoaxKljYSPzhJ6UnNrgGMNZUAW7r5p/FPpA4zKu6o5HsWpixKY9E2hNevcgdq0Bn1csuz8xlZa9XeMChH+VGiNurfOGfra50zR05tU4keKdxLK3t+qRwDsra7IOXdUNmI9d1m6M3bB+caxpxLLiJK1ivclKgOwDJiqWl5mdWaPbYciRYQgtXFmtCzJl8W9rOyhjcF/o1Ns2rw=
#   bucket: "lv285oms-bucket"
#   skip_cleanup: true
#   upload-dir: oms
#   acl: bucket_owner_full_control
#   on:
#     repo: oholovko/oms
after_success:
  - docker --version
 # Do AWS login for ECR
  # language: python
  # python:
  # - "3.5"
  - docker create --name oms-web:latest ${DOCKER_REPOSITORY} && docker cp $TRAVIS_BUILD_DIR/target/OMS.war oms-web:/usr/local/tomcat/webapps/. && docker commit oms-web oms-web:latest
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - $(aws ecr get-login --no-include-email --region us-east-2)
  - docker tag oms-web 851151705021.dkr.ecr.us-east-2.amazonaws.com/repo:latest
  - docker push 851151705021.dkr.ecr.us-east-2.amazonaws.com/repo:latest
