language: java
sudo: false
jdk:
- oraclejdk8
script:
- mvn clean install
deploy:
  - provider: s3
    access_key_id: AWS_ACCESS_KEY_ID
    secret_access_key: AWS_SECRET_KEY
    bucket: "arn:aws:s3:::lv285oms"
env:
  global:
    secure: iKU3WrhrvEiwAsYdZuFAP06GeiTFaXQsVdbAAFq6n8RrFc/MTzsytz5ZDhwO8gbTT0bEJDV8PWoeBdkiXfxKQYQi2rr+I5qqLVWd5Y+nBTEub5K9WaxYdSQsGMcjWYDUNYDpNNa/6uGeUqIs/tlPsOx5smyqaggAirz4+eH2NAh1cG8X62G/ddnnRTP9HrlfJDlP4/cmr6tfRPitJapk8X2tEtLkUzueBvzFqP4SXXhJ3OIxeAc3H903Y63USCYD2rIuWK0pq4Nck0TDK1JMjv7gSQ8zVRfGxui/cVAXsoeBaL3e+XQLajWNgBsG8fyANvv+hy6iFBvCAMKBylNqiW7efKBqRTyqESw+olHPSfuOPMA2BWeKPpUu2BWEYPDU2XnaaIKKto21T6tmQChoUY9FKJhWpZ/jkjLqGCPvH3O2ssgqeHqI5sugSyZkEEiCH40W03ISo2YcnVl7sfceKcV4vbebgnPeC4iB2Lz1ppvXkToCFH4PcEzTCy6VxiGu2L2mzaUuEDOuk7Ueyj1AGb5sgGoTm5ukMup8wJRUMeAQfvsZ7dPT6zFg2KiDiu3vat4lZ5y/dODYqWyrBrw2OMOw4AncXuswTdOX8DdYfdlGC8U8M0hCDQxa8GEOAoQFHBJrCleOkR36JkyA6jbEu5XHOiJ+EtrWDdI0ZXZSlWU=
